disabled_rules:
  - trailing_whitespace
  - identifier_name
  - line_length
  - nesting

opt_in_rules:
  - empty_count

included:
  - Sources

excluded:
  - Carthage
  - Pods

analyzer_rules:
  - explicit_self

colon:
  severity: error

comma:
  severity: error

control_statement:
  severity: error

empty_enum_arguments:
  severity: error

file_length:
  warning: 400
  error: 600

force_cast: warning
force_try:
  severity: warning

for_where:
  severity: error

identifier_name:
  min_length:
    error: 3
  excluded:
    - id

empty_parentheses_with_trailing_closure:
  severity: error

implicit_getter:
  severity: error

large_tuple: 3

leading_whitespace:
  severity: error

legacy_constant:
  severity: error

legacy_constructor:
  severity: error

mark:
  severity: error

opening_brace:
  severity: error

operator_whitespace:
  severity: error

redundant_discardable_let:
  severity: error

redundant_optional_initialization:
  severity: error

redundant_void_return:
  severity: error

return_arrow_whitespace:
  severity: error

statement_position:
  severity: error

switch_case_alignment:
  severity: error

syntactic_sugar:
  severity: error

trailing_comma:
  severity: error

trailing_newline:
  severity: error

trailing_semicolon:
  severity: error

type_body_length:
  - 300
  - 400

type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: iPhone

unneeded_break_in_switch:
  severity: error

unused_closure_parameter:
  severity: error

unused_optional_binding:
  severity: error

vertical_parameter_alignment:
  severity: error

vertical_whitespace:
  severity: error

reporter: "xcode"
